# Generated by Django 4.2.7 on 2023-11-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='author',
            new_name='seller',
        ),
    ]
